# Generated by Django 4.0.8 on 2022-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickstart', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cosmeticsshortname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradecode', models.IntegerField(blank=True, db_column='TradeCode', null=True)),
                ('shorttradename', models.CharField(blank=True, db_column='ShortTradeName', max_length=100, null=True)),
                ('company_code', models.IntegerField(blank=True, db_column='Company_code', null=True)),
                ('trade_name', models.CharField(blank=True, db_column='Trade_name', max_length=1500, null=True)),
            ],
            options={
                'db_table': 'CosmeticsShortName',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField(db_column='Company_code')),
                ('arabicname', models.CharField(blank=True, db_column='ArabicName', max_length=100, null=True)),
                ('englishname', models.CharField(blank=True, db_column='EnglishName', max_length=100, null=True)),
                ('licensetypecode', models.DecimalField(blank=True, db_column='LicenseTypeCode', decimal_places=0, max_digits=12, null=True)),
                ('licensetype', models.CharField(blank=True, db_column='LicenseType', max_length=100, null=True)),
                ('companytypecode', models.DecimalField(blank=True, db_column='CompanyTypeCode', decimal_places=0, max_digits=12, null=True)),
                ('companytype', models.CharField(blank=True, db_column='CompanyType', max_length=100, null=True)),
                ('companystatus', models.CharField(blank=True, db_column='CompanyStatus', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TempCompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempdrug',
            fields=[
                ('tradecode', models.DecimalField(db_column='TradeCode', decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('regno', models.CharField(blank=True, db_column='RegNo', max_length=20, null=True)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=300, null=True)),
                ('license_type_code', models.DecimalField(blank=True, db_column='License_type_code', decimal_places=0, max_digits=12, null=True)),
                ('license_type', models.CharField(blank=True, db_column='License_type', max_length=100, null=True)),
                ('licensestatuscode', models.DecimalField(blank=True, db_column='LicenseStatusCode', decimal_places=0, max_digits=12, null=True)),
                ('licensestatus', models.CharField(blank=True, db_column='LicenseStatus', max_length=100, null=True)),
                ('dosage_formcode', models.DecimalField(blank=True, db_column='Dosage_formCode', decimal_places=0, max_digits=12, null=True)),
                ('dosage_form', models.CharField(blank=True, db_column='Dosage_form', max_length=100, null=True)),
                ('shelflife', models.DecimalField(blank=True, db_column='ShelfLife', decimal_places=0, max_digits=12, null=True)),
                ('markettypecode', models.DecimalField(blank=True, db_column='MarketTypeCode', decimal_places=0, max_digits=12, null=True)),
                ('markettype', models.CharField(blank=True, db_column='MarketType', max_length=100, null=True)),
                ('licflagcode', models.DecimalField(blank=True, db_column='LicFlagCode', decimal_places=0, max_digits=12, null=True)),
                ('licflag', models.CharField(blank=True, db_column='LicFlag', max_length=50, null=True)),
                ('approvenamea', models.CharField(blank=True, db_column='ApproveNameA', max_length=300, null=True)),
                ('manufcode', models.DecimalField(blank=True, db_column='ManufCode', decimal_places=0, max_digits=12, null=True)),
                ('manuf', models.CharField(blank=True, db_column='Manuf', max_length=100, null=True)),
                ('company_code', models.DecimalField(blank=True, db_column='Company_code', decimal_places=0, max_digits=12, null=True)),
                ('legacystatus', models.DecimalField(blank=True, db_column='LegacyStatus', decimal_places=0, max_digits=1, null=True)),
                ('drug_registration_date', models.DateTimeField(blank=True, db_column='Drug_registration_date', null=True)),
                ('drug_registration_expiration_date', models.DateTimeField(blank=True, db_column='Drug_registration_expiration_date', null=True)),
                ('company_profile_id', models.DecimalField(blank=True, db_column='COMPANY_PROFILE_ID', decimal_places=0, max_digits=8, null=True)),
                ('manufcountryid', models.DecimalField(blank=True, db_column='ManufCountryID', decimal_places=0, max_digits=8, null=True)),
                ('manufcountry', models.CharField(blank=True, db_column='ManufCountry', max_length=350, null=True)),
                ('license_holder_company_id', models.DecimalField(blank=True, db_column='LICENSE_HOLDER_COMPANY_ID', decimal_places=0, max_digits=18, null=True)),
                ('license_holder_company', models.CharField(blank=True, db_column='LICENSE_HOLDER_COMPANY', max_length=350, null=True)),
                ('license_holder_country_id', models.DecimalField(blank=True, db_column='LICENSE_HOLDER_COUNTRY_ID', decimal_places=0, max_digits=8, null=True)),
                ('license_holder_country', models.CharField(blank=True, db_column='LICENSE_HOLDER_COUNTRY', max_length=50, null=True)),
                ('f_added', models.BooleanField(blank=True, db_column='F_ADDED', null=True)),
                ('shortname', models.CharField(blank=True, db_column='ShortName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TempDrug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tempdrugsmanufacture',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('manufcode', models.IntegerField(blank=True, db_column='ManufCode', null=True)),
                ('manuf', models.CharField(blank=True, db_column='Manuf', max_length=300, null=True)),
                ('manufcountryid', models.IntegerField(blank=True, db_column='ManufCountryID', null=True)),
                ('manufcountry', models.CharField(blank=True, db_column='ManufCountry', max_length=70, null=True)),
            ],
            options={
                'db_table': 'TempDrugsManufacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('vacation_date', models.DateTimeField(db_column='VACATION_DATE')),
                ('vacation_desc', models.TextField(blank=True, db_column='VACATION_DESC', null=True)),
                ('created_by', models.DecimalField(blank=True, db_column='CREATED_BY', decimal_places=0, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CREATED_DATE', null=True)),
                ('modified_by', models.DecimalField(blank=True, db_column='MODIFIED_BY', decimal_places=0, max_digits=12, null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='MODIFIED_DATE', null=True)),
                ('f_delete', models.BooleanField(blank=True, db_column='F_DELETE', null=True)),
            ],
            options={
                'db_table': 'VACATION',
                'managed': False,
            },
        ),
    ]
