# Generated by Django 4.0.8 on 2022-11-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Cosmeticsshortname',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Sysdiagrams',
        ),
        migrations.DeleteModel(
            name='Tempcompany',
        ),
        migrations.DeleteModel(
            name='Tempdrug',
        ),
        migrations.DeleteModel(
            name='Tempdrugsmanufacture',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
