# Generated by Django 4.0.8 on 2022-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickstart', '0004_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.DecimalField(db_column='ID', decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('old_product_id', models.DecimalField(blank=True, db_column='OLD_PRODUCT_ID', decimal_places=0, max_digits=12, null=True)),
                ('old_reg_no', models.DecimalField(blank=True, db_column='OLD_REG_NO', decimal_places=0, max_digits=12, null=True)),
                ('notification_no', models.CharField(blank=True, db_column='NOTIFICATION_NO', max_length=20, null=True)),
                ('notification_date', models.DateTimeField(blank=True, db_column='NOTIFICATION_DATE', null=True)),
                ('re_notification_date', models.DateTimeField(blank=True, db_column='RE_NOTIFICATION_DATE', null=True)),
                ('product_type_id', models.DecimalField(blank=True, db_column='PRODUCT_TYPE_ID', decimal_places=0, max_digits=12, null=True)),
                ('arabic_name', models.CharField(blank=True, db_column='ARABIC_NAME', max_length=1500, null=True)),
                ('english_name', models.CharField(blank=True, db_column='ENGLISH_NAME', max_length=1500, null=True)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=150, null=True)),
                ('registration_type_id', models.DecimalField(blank=True, db_column='REGISTRATION_TYPE_ID', decimal_places=0, max_digits=12, null=True)),
                ('company_profile_id', models.DecimalField(blank=True, db_column='COMPANY_PROFILE_ID', decimal_places=0, max_digits=12, null=True)),
                ('manufacturing_company_id', models.DecimalField(blank=True, db_column='MANUFACTURING_COMPANY_ID', decimal_places=0, max_digits=12, null=True)),
                ('manufacturing_country_id', models.DecimalField(blank=True, db_column='MANUFACTURING_COUNTRY_ID', decimal_places=0, max_digits=12, null=True)),
                ('applicant_id', models.DecimalField(blank=True, db_column='APPLICANT_ID', decimal_places=0, max_digits=12, null=True)),
                ('license_holder_id', models.DecimalField(blank=True, db_column='LICENSE_HOLDER_ID', decimal_places=0, max_digits=12, null=True)),
                ('license_holder_other', models.CharField(blank=True, db_column='LICENSE_HOLDER_OTHER', max_length=300, null=True)),
                ('license_holder_country_id', models.DecimalField(blank=True, db_column='LICENSE_HOLDER_COUNTRY_ID', decimal_places=0, max_digits=12, null=True)),
                ('trade_mark', models.CharField(blank=True, db_column='TRADE_MARK', max_length=300, null=True)),
                ('physical_state_id', models.DecimalField(blank=True, db_column='PHYSICAL_STATE_ID', decimal_places=0, max_digits=12, null=True)),
                ('physical_state_other', models.CharField(blank=True, db_column='PHYSICAL_STATE_OTHER', max_length=300, null=True)),
                ('colour_id', models.DecimalField(blank=True, db_column='COLOUR_ID', decimal_places=0, max_digits=12, null=True)),
                ('use_purpose_id', models.DecimalField(blank=True, db_column='USE_PURPOSE_ID', decimal_places=0, max_digits=12, null=True)),
                ('purpose_of_use_other', models.CharField(blank=True, db_column='PURPOSE_OF_USE_OTHER', max_length=300, null=True)),
                ('storage_place_id', models.DecimalField(blank=True, db_column='STORAGE_PLACE_ID', decimal_places=0, max_digits=12, null=True)),
                ('shelf_life', models.DecimalField(blank=True, db_column='SHELF_LIFE', decimal_places=0, max_digits=3, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, db_column='EXPIRATION_DATE', null=True)),
                ('appworks_id', models.CharField(blank=True, db_column='APPWORKS_ID', max_length=50, null=True)),
                ('appworks_guid', models.CharField(blank=True, db_column='APPWORKS_GUID', max_length=50, null=True)),
                ('f_expired', models.BooleanField(blank=True, db_column='F_EXPIRED', null=True)),
                ('f_confirmed', models.BooleanField(blank=True, db_column='F_CONFIRMED', null=True)),
                ('f_draft', models.BooleanField(blank=True, db_column='F_DRAFT', null=True)),
                ('f_kit', models.BooleanField(blank=True, db_column='F_KIT', null=True)),
                ('f_export_only', models.BooleanField(blank=True, db_column='F_EXPORT_ONLY', null=True)),
                ('f_flag', models.BooleanField(blank=True, db_column='F_FLAG', null=True)),
                ('f_flag_lab', models.BooleanField(blank=True, db_column='F_FLAG_LAB', null=True)),
                ('f_hold', models.BooleanField(blank=True, db_column='F_HOLD', null=True)),
                ('f_hold_lab', models.BooleanField(blank=True, db_column='F_HOLD_LAB', null=True)),
                ('f_block', models.BooleanField(blank=True, db_column='F_BLOCK', null=True)),
                ('comments', models.CharField(blank=True, db_column='COMMENTS', max_length=1000, null=True)),
                ('created_by', models.DecimalField(blank=True, db_column='CREATED_BY', decimal_places=0, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CREATED_DATE', null=True)),
                ('modified_by', models.DecimalField(blank=True, db_column='MODIFIED_BY', decimal_places=0, max_digits=12, null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='MODIFIED_DATE', null=True)),
                ('f_delete', models.BooleanField(blank=True, db_column='F_DELETE', null=True)),
                ('f_inprocess', models.BooleanField(blank=True, db_column='F_INPROCESS', null=True)),
                ('license_holder_syskey', models.DecimalField(blank=True, db_column='LICENSE_HOLDER_syskey', decimal_places=0, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.DecimalField(db_column='ID', decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('product_id', models.DecimalField(blank=True, db_column='PRODUCT_ID', decimal_places=0, max_digits=12, null=True)),
                ('product_colour', models.CharField(blank=True, db_column='PRODUCT_COLOUR', max_length=200, null=True)),
                ('fragrance', models.CharField(blank=True, db_column='FRAGRANCE', max_length=200, null=True)),
                ('flavor', models.CharField(blank=True, db_column='FLAVOR', max_length=200, null=True)),
                ('barcode', models.CharField(blank=True, db_column='BARCODE', max_length=30, null=True)),
                ('appworks_id', models.CharField(blank=True, db_column='APPWORKS_ID', max_length=50, null=True)),
                ('appworks_guid', models.CharField(blank=True, db_column='APPWORKS_GUID', max_length=50, null=True)),
                ('modified_by', models.DecimalField(blank=True, db_column='MODIFIED_BY', decimal_places=0, max_digits=12, null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='MODIFIED_DATE', null=True)),
                ('created_by', models.DecimalField(blank=True, db_column='CREATED_BY', decimal_places=0, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CREATED_DATE', null=True)),
                ('f_delete', models.BooleanField(blank=True, db_column='F_DELETE', null=True)),
            ],
            options={
                'db_table': 'PRODUCT_DETAILS',
                'managed': False,
            },
        ),
    ]
