# Generated by Django 4.0.8 on 2022-11-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='COSM.PRODUCT',
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table='COSM.PRODUCT_DETAILS',
        ),
    ]
