# Generated by Django 4.0.8 on 2022-11-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_product_table_alter_productdetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='PRODUCT',
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table='PRODUCT_DETAILS',
        ),
    ]
