# Generated by Django 4.0.8 on 2022-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_product_table_alter_productdetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='COSM].[PRODUCT',
        ),
    ]
