# Generated by Django 4.0.8 on 2022-11-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productdetails',
            table='COSM].[PRODUCT_DETAILS',
        ),
    ]
