# Generated by Django 4.0.8 on 2022-11-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_productbatches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBatches',
        ),
    ]
