# Generated by Django 4.0.8 on 2022-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_delete_productbatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.DecimalField(db_column='ID', decimal_places=0, max_digits=12)),
                ('product_id', models.DecimalField(db_column='PRODUCT_ID', decimal_places=0, max_digits=12)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=50, null=True)),
                ('production_date', models.DateTimeField(blank=True, db_column='PRODUCTION_DATE', null=True)),
                ('expiration_date', models.DateTimeField(blank=True, db_column='EXPIRATION_DATE', null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='QUANTITY', decimal_places=0, max_digits=12, null=True)),
                ('lkup_uom_id', models.DecimalField(blank=True, db_column='LKUP_UOM_ID', decimal_places=0, max_digits=12, null=True)),
                ('created_by', models.DecimalField(blank=True, db_column='CREATED_BY', decimal_places=0, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CREATED_DATE', null=True)),
                ('modified_by', models.DecimalField(blank=True, db_column='MODIFIED_BY', decimal_places=0, max_digits=12, null=True)),
                ('modified_date', models.DateTimeField(blank=True, db_column='MODIFIED_DATE', null=True)),
                ('f_delete', models.BooleanField(blank=True, db_column='F_DELETE', null=True)),
            ],
            options={
                'db_table': 'COSM].[PRODUCT_BATCHES',
                'managed': False,
            },
        ),
    ]
